### ISSUE TITLE
Bug with camera

### ISSUE THREAD

**Issue by CEOXeon** [SuhasDissa/Food-E-App#36]
My Device:
Android 12 with Magisk
Samsung Galaxy A41 
One UI 4.1

When I try opening the scanner shows this error and the screen is black with the scanner overlay:

2023-06-13 20:07:03.116 32244 32354 app.suhasdissa.foode E AndroidRuntime : FATAL EXCEPTION: cs-init
Process: app.suhasdissa.foode, PID: 32244
java.lang.RuntimeException: java.lang.NoSuchMethodException: Q1.d.values []
	at java.lang.Enum.enumValues(Enum.java:272)
	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
	at java.lang.Enum$1.create(Enum.java:279)
	at java.lang.Enum$1.create(Enum.java:277)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
	at java.lang.Enum.getSharedConstants(Enum.java:291)
	at java.lang.Class.getEnumConstantsShared(Class.java:2461)
	at java.util.EnumMap.getKeyUniverse(EnumMap.java:754)
	at java.util.EnumMap.<init>(EnumMap.java:134)
	at com.budiyev.android.codescanner.n.<init>(Unknown Source:31)
	at com.budiyev.android.codescanner.e.run(SourceFile:602)
Caused by: java.lang.NoSuchMethodException: Q1.d.values []
	at java.lang.Class.getMethod(Class.java:2103)
	at java.lang.Class.getDeclaredMethod(Class.java:2081)
	at java.lang.Enum.enumValues(Enum.java:269)
	... 10 more

**Comment by SuhasDissa** [comment]
Seems that the error only occurs in the release build of this app. I'm working on fixing it now. Thanks for reporting :)

**Comment by SuhasDissa** [comment]
Fixed the issue in the [latest release](https://github.com/SuhasDissa/Food-E-App/releases/tag/v3.2)

I'm so sorry that the latest version of this app has been causing problems for you. I take full responsibility for this, as I released the app without thorough testing.
I know this has been inconvenient for you, and I sincerely apologize
